//
//  ${file_name}
//
//  Copyright (c) ${year} FiftyThree, Inc. All rights reserved.
//
//  WARNING: Do NOT manually edit this file.
//  This file was generated by js2model from a JSON schema
//

#pragma once

% for classDef in models:
#import "${classDef.header_file}"
% endfor
