#!/usr/bin/env python

# Copyright (c) 2015 Thomson Reuters
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

try:
    import jsonref
except ImportError:
    print
    print 'Could not import "jsonref" library.'
    print 'For installation instructions, see: https://github.com/ahupp/python-magic'
    print 'ie.'
    print 'brew install python'
    print 'pip install jsonref'
    print
    sys.exit(1)

try:
    import mako
except ImportError:
    print
    print 'Could not import "mako" library.'
    print 'For installation instructions, see: https://github.com/ahupp/python-magic'
    print 'ie.'
    print 'brew install python'
    print 'pip install mako'
    print
    sys.exit(1)

try:
    import jsonschema
except ImportError:
    print
    print 'Could not import "jsonschema" library.'
    print 'For installation instructions, see: https://github.com/ahupp/python-magic'
    print 'ie.'
    print 'brew install python'
    print 'pip install jsonschema'
    print
    sys.exit(1)

import js2model

from js2model import main

if __name__ == "__main__":
    exit(main())
